spring:
  profiles:
    active: 
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dev1
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-test
# 请保存为UTF-8格式
